In [7]:
import numpy as np

In [8]:
total = list(range(1,10))

In [9]:
def diff(li1, li2): 
    return (list(set(li1) - set(li2)))

In [24]:
# Enter the appropriate numbers in their position by removing zeros.

#  sample: np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
#                    [6, 0, 0, 1, 9, 5, 0, 0, 0],
#                    [0, 9, 8, 0, 0, 0, 0, 6, 0],
#                    [8, 0, 0, 0, 6, 0, 0, 0, 3],
#                    [4, 0, 0, 8, 0, 3, 0, 0, 1],
#                    [7, 0, 0, 0, 2, 0, 0, 0, 6],
#                    [0, 6, 0, 0, 0, 0, 2, 8, 0],
#                    [0, 0, 0, 4, 1, 9, 0, 0, 5],
#                    [0, 0, 0, 0, 8, 0, 0, 7, 9]])




data = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0]])




In [25]:
data

array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 7, 9]])

In [26]:

# This code will find all the possible values for an empty position. 
# For an empty position, this code will delete the values present in the row, column and 3*3 square of that position.



def possi_val(i,j):
    possib_vals = diff(total,data[i])
    possib_vals = diff(possib_vals,data[:,j])
    if i%3 == 0:
        if j%3 == 0:
            possib_vals = diff(possib_vals,(data[i:i+3,j:j+3]).flatten())
        if j%3 == 1:
            possib_vals = diff(possib_vals,(data[i:i+3,j-1:j+2]).flatten())            
        if j%3 == 2:
            possib_vals = diff(possib_vals,(data[i:i+3,j-2:j+1]).flatten())
    if i%3 == 1:
        if j%3 == 0:
            possib_vals = diff(possib_vals,(data[i-1:i+2,j:j+3]).flatten())
        if j%3 == 1:
            possib_vals = diff(possib_vals,(data[i-1:i+2,j-1:j+2]).flatten())
        if j%3 == 2:
            possib_vals = diff(possib_vals,(data[i-1:i+2,j-2:j+1]).flatten())
    if i%3 == 2:
        if j%3 == 0:
            possib_vals = diff(possib_vals,(data[i-2:i+1,j:j+3]).flatten())
        if j%3 == 1:
            possib_vals = diff(possib_vals,(data[i-2:i+1,j-1:j+2]).flatten())
        if j%3 == 2:
            possib_vals = diff(possib_vals,(data[i-2:i+1,j-2:j+1]).flatten())
    return possib_vals

In [27]:

# For the position we are checking i.e (i,j), it will find all the possible values of the empty positions in the 3*3 
# square it lies and combine all of them to form "box_need".
# In those possible values i.e "box_need", if there any number appeared only once, it will be added to "box_unique".
# If any number in "box_unique" is present in the list of possible values of the position we are looking for 
# i.e "possi_val(i,j)", it will fix that number to that position(i,j).


def no_chance_box(i,j):
    if i%3 == 0:
        if j%3 == 0:
# Here 'box_need' means, all the possible numbers that need for the 3*3 square in which the position lies.
            box_need=[]
            for k in range(i,i+3):
                for l in range(j,j+3):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
# 'box_unique' will find if there any possible number that has appeared only one time.
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]

        if j%3 == 1:
            box_need=[]
            for k in range(i,i+3):
                for l in range(j-1,j+2):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]
        if j%3 == 2:
            box_need=[]
            for k in range(i,i+3):
                for l in range(j-2,j+1):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])

            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]
    if i%3 == 1:
        if j%3 ==0:
            box_need=[]
            for k in range(i-1,i+2):
                for l in range(j,j+3):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])

            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]
        if j%3 == 1:
            box_need=[]
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]

        if j%3 == 2:
            box_need=[]
            for k in range(i-1,i+2):
                for l in range(j-2,j+1):
                    if data[k,l]==0:
                        box_need+=possi_val(k,l)
            box_unique=[]
            for p in range(len(box_need)):
                if box_need.count(box_need[p])==1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j]=box_unique[n]

    if i%3 == 2:
        if j%3 == 0:
            box_need  = []
            for k in range(i-2,i+1):
                for l in range(j,j+3):
                    if data[k,l] == 0:
                        box_need += possi_val(k,l)
            box_unique = []
            for p in range(len(box_need)):
                if box_need.count(box_need[p]) == 1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j] = box_unique[n]

        if j%3 == 1:
            box_need  = []
            for k in range(i-2,i+1):
                for l in range(j-1,j+2):
                    if data[k,l] == 0:
                        box_need += possi_val(k,l)
            box_unique = []
            for p in range(len(box_need)):
                if box_need.count(box_need[p]) == 1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j] = box_unique[n]
        if j%3 == 2:
            box_need  = []
            for k in range(i-2,i+1):
                for l in range(j-2,j+1):
                    if data[k,l] == 0:
                        box_need += possi_val(k,l)
            box_unique = []
            for p in range(len(box_need)):
                if box_need.count(box_need[p]) == 1:
                    box_unique.append(box_need[p])
            
            for n in range(len(box_unique)):
                if box_unique[n] in possi_val(i,j):
                    data[i,j] = box_unique[n]

In [28]:
# Earlier we check for the 3*3 square. Now we find for row.
# For the position we are checking i.e (i,j), it will find all the possible values of the empty positions in i'th row
# and combine them to form "row_need".
# In those possible values, if there any number appeared only once, it will be added to "row_unique".
# If any number in "row_unique" is present in the list of possible values of the position we are looking for 
# i.e "possi_val(i,j)", it will fix that number to that position(i,j).



def no_chance_row(i,j):
    row_need=[]
    for k in range(0,9):
        if data[i,k]==0:
            row_need+=possi_val(i,k)
    row_unique=[]
    for p in range(len(row_need)):
        if row_need.count(row_need[p])==1:
            row_unique.append(row_need[p])
    for n in range(len(row_unique)):
        if row_unique[n] in possi_val(i,j):
            data[i,j]=row_unique[n]

In [29]:
# Similarly, we also check for column.
# For the position we are checking i.e (i,j), it will find all the possible values of the empty positions in j'th column 
# and combine them to form "col_need".
# In those possible values, if there any number appeared only once, it will be added to "col_unique".
# If any number in 'col_unique' is present in the list of possible values of the position we are looking for 
# i.e 'possi_val(i,j)', it will fix that number to that position(i,j).




def no_chance_col(i,j):
    col_need=[]
    for k in range(0,9):
        if data[k,j]==0:
            col_need+=possi_val(k,j)
    col_unique=[]
    for p in range(len(col_need)):
        if col_need.count(col_need[p])==1:
            col_unique.append(col_need[p])
    for n in range(len(col_unique)):
        if col_unique[n] in possi_val(i,j):
            data[i,j]=col_unique[n]

In [35]:
for q in range(5):
    non_zeros = np.count_nonzero(data)
    for z in range(20):
        if np.count_nonzero(data) != 81:
            for i in range(0,9):
                for j in range(0,9):
                    if data[i,j] == 0:
                        k = possi_val(i,j)
                        if len(k)==1:
                            data[i,j] = k[0]
        else:
            break
    if np.count_nonzero(data) != 81:
        for z in range(20):
            if np.count_nonzero(data) != 81:
                for i in range(0,9):
                    for j in range(0,9):
                        if data[i,j] == 0:
                            no_chance_box(i,j)
            else:
                break
    if np.count_nonzero(data) != 81:
        for z in range(20):
            if np.count_nonzero(data) != 81:
                for i in range(0,9):
                    for j in range(0,9):
                        if data[i,j] == 0:
                            no_chance_row(i,j)
            else:
                break
    if np.count_nonzero(data) != 81:
        for z in range(20):
            if np.count_nonzero(data) != 81:
                for i in range(0,9):
                    for j in range(0,9):
                        if data[i,j] == 0:
                            no_chance_col(i,j)
    non_zeros_after = np.count_nonzero(data)
    if (non_zeros == non_zeros_after) or (non_zeros_after == 81):
        break
if non_zeros_after != 81:
    print("Sorry, i can't find solution with these numbers. Please enter minimum appropriate numbers.")
print('The solution that I find is: \n\n',data)

The solution that I find is: 

 [[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
